# Setup
title:               José Ramón García
tagline:             'Prospector Laboral'
description:         'Conectando ofertas y demandas de empleo'
url:                 http://jrgarcia.es
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              José Ramón García
  url:               https://twitter.com/joseramongg
  email:             jose@jrgarcia.es

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0

