# Setup
title:               José Ramón García
tagline:             'Prospector Laboral'
description:         'Prospector Laboral en el Programa Acceder de la Fundación Secretariado Gitano de Santiago de Compostela'
url:                 https://jrgarcia.es
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              José Ramón García
  url:               https://jrgarcia.es
  email:             jose@jrgarcia.es

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

theme: jekyll-theme-minimal