theme: jekyll-theme-minimal
title: _______________________
logo: fotojr.jpeg
description: [Soy José Ramón García | Bienvenid@s a mi web minimalista si es que a esto se le puede llamar una web. ;)]
google_analytics:
github:
  is_project_page: false
  
 
