# Setup
title:               José Ramón García
tagline:             'Prospector Laboral'
description:         'Prospector Laboral del Programa Acceder. Es un servicio público de intermediación laboral dirigido a empresas y desempleados/as, con la finalidad de poner en contacto ofertas y demandas de empleo.'
url:                 https://jrgarcia.es/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              José Ramón García
  url:               https://jrgarcia.es
  email:             jose@jrgarcia.es

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
