# Setup
title:               José Ramón García
tagline:             'Prospector Laboral'
description:         'ACCEDER es un servicio público de intermediación laboral dirigido a empresas y a personas, con la finalidad de poner en contacto ofertas y demandas de empleo.'
url:                 https://jrgarcia.es/
baseurl:             ''
paginate:            5
paginate_path: "/page:num/"
permalink:           pretty

# About/contact
author:
  name:              José Ramón García
  url:               https://jrgarcia.es
  email:             jose@jrgarcia.es

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
