theme: jekyll-theme-minimal
logo: /assets/img/logo.png
description: [Bienvenid@s a mi web minimalista si es que a esto se le puede llamar una web. ;)]
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
